"""
Attaches a themed decorative SVG (media_url) to Reading and Writing
questions whose prompt matches one of 8 topic keyword buckets (nature,
ocean/environment, school, sport, food, travel, weather, community),
mirroring what backfill_question_images.py already does for Numeracy
diagrams -- except here the image never carries information relevant to
the answer, since R/W/LC questions aren't the kind of question a diagram
can meaningfully solve. It's purely a topic illustration (see
database/text_diagrams.py) to make the practice quiz page more inviting.

Each matched question gets its own uniquely generated image (seeded by
question_id, so colour/position/layout vary) rather than every question
in a theme sharing one file. Questions whose prompt doesn't match any
theme -- and ALL Language Conventions questions, which are too abstract
(spelling/grammar) for topic theming -- get no image at all rather than a
generic filler.

Re-runnable: recomputes every Reading/Writing/Language Conventions
question from scratch each time (clears media_url first), since the
theme detection or generator may change. Numeracy rows are untouched.

Usage:
    python backfill_text_domain_images.py
"""

import glob
import os

from config import get_connection
import text_diagrams as td

IMAGES_DIR = os.path.join(os.path.dirname(__file__), "..", "stage1-initial-design-craft", "images", "questions")
MEDIA_URL_PREFIX = "/images/questions"

os.makedirs(IMAGES_DIR, exist_ok=True)

# Order matters: first matching theme wins. Keep more specific themes
# (e.g. "ocean") ahead of anything that could false-positive on a broader
# one.
THEME_KEYWORDS = [
    ("ocean", ["plastic waste", "ocean", "recycl", "native wildlife", "electric vehicle",
                "green space", "environment"]),
    ("nature", ["animal", "zoo", "fox", "wildlife", "elephant", "forest", "plant", "garden",
                "vegetable", "pet ", "keeping a pet", "bird"]),
    ("school", ["school", "homework", "classroom", "uniform", "canteen", "subject", "teacher",
                "student volunteer"]),
    ("sports", ["sport", "team", "race", "exercise", "match", "game", "training"]),
    ("food", ["recipe", "banana bread", "snack", "cooking", "baking", "food", "meal"]),
    ("travel", ["bus", "city", "journey", "travel", "transport", "explore", "visiting a new"]),
    ("weather", ["weather", "forecast", "season", "summer", "rainy day", "daylight saving"]),
    ("community", ["neighbour", "family tradition", "birthday", "volunteer", "kindness",
                    "friend", "gift", "community event", "musical instrument"]),
]


def detect_theme(prompt):
    low = prompt.lower()
    for theme, keywords in THEME_KEYWORDS:
        if any(kw in low for kw in keywords):
            return theme
    return None


def clear_stale_files():
    """Remove images generated by earlier versions of this script (shared
    per-theme files, per-domain defaults) so nothing orphaned is left on disk."""
    for pattern in ("theme-*.svg",):
        for path in glob.glob(os.path.join(IMAGES_DIR, pattern)):
            os.remove(path)


def main():
    conn = get_connection()
    cursor = conn.cursor()

    # Recompute from scratch: clear any media_url this script previously
    # set on R/W/LC rows (leaves Numeracy's media_url alone).
    cursor.execute(
        """
        UPDATE q SET q.media_url = NULL
        FROM dbo.questions q
        JOIN dbo.domains d ON d.domain_id = q.domain_id
        WHERE d.code IN ('R', 'W', 'LC')
        """
    )
    conn.commit()
    clear_stale_files()

    cursor.execute(
        """
        SELECT q.question_id, d.code, q.prompt
        FROM dbo.questions q
        JOIN dbo.domains d ON d.domain_id = q.domain_id
        WHERE d.code IN ('R', 'W', 'LC')
        """
    )
    rows = cursor.fetchall()
    print(f"Scanning {len(rows)} Reading/Writing/Language Conventions questions...")

    matched = 0
    removed = 0
    per_theme = {}
    update_cursor = conn.cursor()

    for question_id, domain_code, prompt in rows:
        theme = None if domain_code == "LC" else detect_theme(prompt)

        if theme is None:
            # No confident topic match -- leave the question without an
            # image rather than force a generic filler.
            removed += 1
            continue

        svg_content = td.THEMES[theme](seed=question_id)
        filename = f"q{question_id}.svg"
        with open(os.path.join(IMAGES_DIR, filename), "w", encoding="utf-8") as f:
            f.write(svg_content)

        media_url = f"{MEDIA_URL_PREFIX}/{filename}"
        update_cursor.execute(
            "UPDATE dbo.questions SET media_url = ? WHERE question_id = ?",
            media_url, question_id,
        )
        matched += 1
        per_theme[theme] = per_theme.get(theme, 0) + 1

    conn.commit()
    conn.close()

    print(f"Attached a unique image to {matched} of {len(rows)} questions.")
    print(f"Left {removed} questions without an image (no confident topic match).")
    for name, count in sorted(per_theme.items(), key=lambda kv: -kv[1]):
        print(f"  {name}: {count}")


if __name__ == "__main__":
    main()
